services:
  - type: web
    runtime: image
    name: ss-gtm-preview
    image:
      url: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /healthy
    envVars:
      - key: RUN_AS_PREVIEW_SERVER
        value: "true"
  - type: web
    runtime: image
    name: ss-gtm
    image:
      url: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    healthCheckPath: /healthy
    envVars:
      - key: PREVIEW_SERVER_URL
        value: https://ss-gtm-preview.onrender.com
